### ISSUE TITLE
Deploy Master Branch automatically to Github

### ISSUE THREAD

**Issue by mariobehling** [yacy/yacy_grid_mcp#15]
In order to get this project working we need to establish a DevOps flow. Apart from getting a Heroku deployment of the development branch, the goal is to have a continuous Master branch deployment to the Google cloud with Kubernetes. Please implement this.

**Comment by nikhilrayaprolu** [comment]
@mariobehling this cannot be automatically deployed to GitHub.
GitHub supports only static page deployments or frontend related projects.
But we could automatically deploy this project to Heroku or other cloud providers.

**Comment by nikhilrayaprolu** [comment]
@mariobehling I understood it now, that we have to deploy to Google cloud. The title of this issue is misleading.

**Comment by mariobehling** [comment]
Ok, good. Yes the idea is to have the master branch run on Google Cloud.
