### ISSUE TITLE
YaCy & YaCy Grid English Forum?

### ISSUE THREAD

**Issue by Outstep** [yacy/yacy_grid_mcp#30]
Hello,

I have just started testing the YaCy Search Engine for possible use in my current project but have now also just found out about the "YaCy Grid" which is supposed to be the Second Generation YaCy Search Engine.

I do not have a feel yet for how the Grid version is better and would like to find out more but cannot find an English Forum to discuss it with the only forum available in German and I cannot read German to register.

Is there any alternatives?

Thanks, and have a great day

**Comment by mariobehling** [comment]
Sorry, there is no English forum yet. The team will consider it. In the meantime you can open new threads in the existing forum and ask in English. Thanks.
