### ISSUE TITLE
stop_rabbitmq.sh file do not stops RabbitMQ server.

### ISSUE THREAD

**Issue by praveenojha33** [yacy/yacy_grid_mcp#32]
stop_rabbitmq.sh in bin folder file do not stops RabbitMQ server.
Suppose I do not start RabbitMQ server according to configuration defined in YaCy Grid setup. So to do that I have to stop the server and then use start_rabbitmq.py setup to start it. But when I use stop_rabbitmq.sh file to stop the RabbitMQ server,it do not work and the server remains open on http://127.0.0.1:15672/.
@Orbiter Please review this issue.Can I work on it. Further the start_rabbitmq.py file do not configure rabbitmq according to setup when YaCy Grid is already running.

**Comment by Orbiter** [comment]
The stop script worked for me. Maybe your environment is a bit different.
As you can see from the pipe in the stop_rabbitmq.sh script, there is just a kill on the pid.

Please debug this in detail, find out what is the cause in your environment and add a patch.

**Comment by praveenojha33** [comment]
It is working for me now.
