### ISSUE TITLE
Deploy dev branch to Heroku for testing

### ISSUE THREAD

**Issue by mariobehling** [yacy/yacy_grid_mcp#33]
We need to be able to test. Please create a Heroku instance.

**Comment by praveenojha33** [comment]
I am following this article https://devcenter.heroku.com/articles/deploying-gradle-apps-on-heroku. I was getting this error earlier
![image](https://user-images.githubusercontent.com/25537606/42980296-60e9d318-8bf4-11e8-9dd6-7e0acc7ccf33.png)
 but after following the solution from this issue https://github.com/yacy/yacy_grid_mcp/issues/22
I am getting this error on heroku 
![image](https://user-images.githubusercontent.com/25537606/42981389-7e4fb22e-8bf9-11e8-803b-18a0e74bfa16.png)
This is my current project https://github.com/praveenojha33/yacy_grid_mcp
Here is my `build.gradle` file https://github.com/praveenojha33/yacy_grid_mcp/blob/master/build.gradle
and the content of my Procfile is
`web: java -Dserver.port=$PORT $JAVA_OPTS -jar build/libs/yacy_grid_mcp-0.0.1-SNAPSHOT.jar`

**Comment by praveenojha33** [comment]
Locally running `heroku local web` command this error
![image](https://user-images.githubusercontent.com/25537606/42980501-49ba0360-8bf5-11e8-814e-cb631dc10150.png)

**Comment by Orbiter** [comment]
Classpath settings must be terribly wrong. Thats possibly an infrastructure problem. Please have a look how other Java projects are doing this.

**Comment by mariobehling** [comment]
Duplicate to https://github.com/yacy/yacy_grid_mcp/issues/22
